In [ ]:
# !wget -O "animal_breed_classification_ai_challenge-dataset.zip" "https://dockship-job-models.s3.ap-south-1.amazonaws.com/6707c47a761bdd2f3c52480c3fd3a6fa?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=AKIAIDOPTEUZ2LEOQEGQ%2F20210427%2Fap-south-1%2Fs3%2Faws4_request&X-Amz-Date=20210427T145609Z&X-Amz-Expires=1800&X-Amz-Signature=8274f524a75d7be671dd77f2f77cb06a5bef87b2f249621e1bfdfc37c599c347&X-Amz-SignedHeaders=host&response-content-disposition=attachment%3B%20filename%3D%22animal_breed_classification_ai_challenge-dataset.zip%22"

In [ ]:
import matplotlib.pyplot as plt
import numpy as np
import tensorflow
import keras 
from tensorflow.keras.layers import Dense,Input,Conv2D,Flatten ,MaxPooling2D
from tensorflow.keras.preprocessing import image
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from keras.preprocessing.image import  img_to_array, load_img
from tensorflow.keras.models import Model,Sequential
from tensorflow.keras.optimizers import Adam, SGD
#Importing All libararies
from PIL import Image
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

import cv2
import random
import os
import pandas as pd
import tensorflow as tf
from tensorflow.keras import layers
from tensorflow.keras.layers import Conv2D,Flatten,Dense
from tensorflow.keras import models
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras.applications import ResNet50,EfficientNetB3,InceptionResNetV2,VGG16, NASNetLarge, NASNetMobile,ResNet152,MobileNetV2
from tensorflow.keras.utils import plot_model
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix , f1_score
from PIL import Image
import sys

In [ ]:
# import shutil
# shutil.unpack_archive("/content/animal_breed_classification_ai_challenge-dataset.zip", "/content/drive/MyDrive/animal")

In [ ]:
# import zipfile
# with zipfile.ZipFile('/content/animal_breed_classification_ai_challenge-dataset.zip', 'r') as zip_ref:
#     zip_ref.extractall('/content/drive/MyDrive/animal ')

In [ ]:
#import and save images in the directory in form of dataframe.
import os
image_id = []
object_type = []
dir = '/content/drive/MyDrive/animal/TRAIN/'
# listdir() returns a list containing the names of the entries in the directory given by path
for dirname in os.listdir(dir):
    if dirname!='.DS_Store':
        for filename in os.listdir(dir+dirname):
              image_id.append(dir+dirname+'/'+filename)
              object_type.append(dirname)

In [ ]:
print(os.listdir(dir))

['abyssinian', 'american_bulldog', 'american_pit_bull_terrier', 'basset_hound', 'beagle', 'bengal', 'birman', 'bombay', 'boxer', 'british_shorthair', 'chihuahua', 'egyptian_mau', 'english_cocker_spaniel', 'english_setter', 'german_shorthaired', 'great_pyrenees', 'havanese', 'japanese_chin', 'keeshond', 'leonberger', 'maine_coon', 'miniature_pinscher', 'newfoundland', 'persian', 'pomeranian', 'pug', 'ragdoll', 'russian_blue', 'saint_bernard', 'samoyed', 'scottish_terrier', 'shiba_inu', 'siamese', 'sphynx', 'staffordshire_bull_terrier', 'wheaten_terrier', 'yorkshire_terrier']

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
import pandas as pd
df = pd.DataFrame(list(zip(image_id, object_type)),columns = ['ImageID','Type'])

In [ ]:
df

                                                ImageID               Type
0     /content/drive/MyDrive/animal/TRAIN/abyssinian...         abyssinian
1     /content/drive/MyDrive/animal/TRAIN/abyssinian...         abyssinian
2     /content/drive/MyDrive/animal/TRAIN/abyssinian...         abyssinian
3     /content/drive/MyDrive/animal/TRAIN/abyssinian...         abyssinian
4     /content/drive/MyDrive/animal/TRAIN/abyssinian...         abyssinian
...                                                 ...                ...
5885  /content/drive/MyDrive/animal/TRAIN/yorkshire_...  yorkshire_terrier
5886  /content/drive/MyDrive/animal/TRAIN/yorkshire_...  yorkshire_terrier
5887  /content/drive/MyDrive/animal/TRAIN/yorkshire_...  yorkshire_terrier
5888  /content/drive/MyDrive/animal/TRAIN/yorkshire_...  yorkshire_terrier
5889  /content/drive/MyDrive/animal/TRAIN/yorkshire_...  yorkshire_terrier

[5890 rows x 2 columns]

In [ ]:
df = df.sample(frac=1).reset_index(drop=True)

In [ ]:
df

                                                ImageID                       Type
0     /content/drive/MyDrive/animal/TRAIN/newfoundla...               newfoundland
1     /content/drive/MyDrive/animal/TRAIN/bengal/62.jpg                     bengal
2     /content/drive/MyDrive/animal/TRAIN/abyssinian...                 abyssinian
3     /content/drive/MyDrive/animal/TRAIN/american_b...           american_bulldog
4     /content/drive/MyDrive/animal/TRAIN/miniature_...         miniature_pinscher
...                                                 ...                        ...
5885  /content/drive/MyDrive/animal/TRAIN/bombay/132...                     bombay
5886  /content/drive/MyDrive/animal/TRAIN/chihuahua/...                  chihuahua
5887  /content/drive/MyDrive/animal/TRAIN/russian_bl...               russian_blue
5888  /content/drive/MyDrive/animal/TRAIN/american_p...  american_pit_bull_terrier
5889  /content/drive/MyDrive/animal/TRAIN/siamese/73...                    siamese

[5890 rows x 2 columns]

In [ ]:
inp = df['ImageID']
out = df['Type']

In [ ]:
train_in,test_in,train_out,test_out = train_test_split(inp,out,random_state = 42,test_size = 0.1,stratify = out)      #splitting the data set

In [ ]:
#Create an object from image data generator
data_gen = ImageDataGenerator(
                    rotation_range = 100,
                    width_shift_range = 0.2,
                    height_shift_range = 0.2,
                    shear_range = 0.2,
                    zoom_range = 0.2,
                    horizontal_flip = True,
                    vertical_flip = True,
                    fill_mode = 'nearest'
)

In [ ]:
#catenation of training input and output
train_x = pd.concat([train_in,train_out],axis=1)

In [ ]:
train_x

                                                ImageID                Type
1969  /content/drive/MyDrive/animal/TRAIN/german_sho...  german_shorthaired
2570  /content/drive/MyDrive/animal/TRAIN/wheaten_te...     wheaten_terrier
4323  /content/drive/MyDrive/animal/TRAIN/abyssinian...          abyssinian
3493  /content/drive/MyDrive/animal/TRAIN/bengal/42.jpg              bengal
4965  /content/drive/MyDrive/animal/TRAIN/japanese_c...       japanese_chin
...                                                 ...                 ...
987   /content/drive/MyDrive/animal/TRAIN/havanese/1...            havanese
653   /content/drive/MyDrive/animal/TRAIN/leonberger...          leonberger
370   /content/drive/MyDrive/animal/TRAIN/bombay/136...              bombay
5583  /content/drive/MyDrive/animal/TRAIN/birman/24.jpg              birman
4440  /content/drive/MyDrive/animal/TRAIN/siamese/15...             siamese

[5301 rows x 2 columns]

In [ ]:
#Image dataframe in sequence 
df = train_x.sample(frac=1).reset_index(drop= True)

In [ ]:
df.reset_index(drop=True, inplace=True)

In [ ]:
df

                                                ImageID                        Type
0     /content/drive/MyDrive/animal/TRAIN/keeshond/9...                    keeshond
1     /content/drive/MyDrive/animal/TRAIN/staffordsh...  staffordshire_bull_terrier
2     /content/drive/MyDrive/animal/TRAIN/persian/45...                     persian
3     /content/drive/MyDrive/animal/TRAIN/pomeranian...                  pomeranian
4     /content/drive/MyDrive/animal/TRAIN/newfoundla...                newfoundland
...                                                 ...                         ...
5296  /content/drive/MyDrive/animal/TRAIN/havanese/6...                    havanese
5297  /content/drive/MyDrive/animal/TRAIN/scottish_t...            scottish_terrier
5298  /content/drive/MyDrive/animal/TRAIN/basset_hou...                basset_hound
5299  /content/drive/MyDrive/animal/TRAIN/persian/99...                     persian
5300  /content/drive/MyDrive/animal/TRAIN/newfoundla...                newfoundland

[5301 rows x 2 columns]

In [ ]:
#train images from whole dataset remain after spiliting 
train_generator = data_gen.flow_from_dataframe(
                    train_x ,x_col = "ImageID",y_col = "Type",
                    target_size = (200,200),
                    batch_size = 8)

Found 5301 validated image filenames belonging to 37 classes.

In [ ]:
#cancatinate the test input and test output 
test_x = pd.concat([test_in,test_out],axis=1)

In [ ]:
#no. of image for  validation after splittting
#image size (200,200,3)
val_generator = data_gen.flow_from_dataframe(
                    test_x,x_col = "ImageID",y_col = "Type",
                    target_size = (200,200),
                    batch_size = 8)

Found 589 validated image filenames belonging to 37 classes.

In [ ]:
#Using EfficientNetB0 as transfer learining model
model = models.Sequential()
model.add(EfficientNetB3(input_shape = (200,200, 3), include_top = False, weights = 'imagenet'))
model.add(layers.GlobalAvgPool2D())
model.add(layers.Flatten())
model.add(layers.Dense(100, activation = 'relu'))
model.add(layers.Dense(100, activation = 'relu'))
model.add(layers.Dropout(0.2))
model.add(Dense(37, activation = 'softmax'))

In [ ]:
#complile of model with categorical crossentropy and adam optimizer with learning rate 0.001
model.compile(loss = 'categorical_crossentropy',
             optimizer = Adam(learning_rate = 0.0001),
             metrics = ['accuracy'])

In [ ]:
#Fitting the model with epoch 10 and batch size 64
history = model.fit(train_generator,epochs = 10,
                    validation_data = val_generator)

Epoch 1/10
663/663 [==============================] - 230s 320ms/step - loss: 3.2689 - accuracy: 0.1352 - val_loss: 1.1831 - val_accuracy: 0.7436
Epoch 2/10
663/663 [==============================] - 208s 313ms/step - loss: 1.5269 - accuracy: 0.5722 - val_loss: 0.6644 - val_accuracy: 0.8234
Epoch 3/10
663/663 [==============================] - 208s 314ms/step - loss: 1.1155 - accuracy: 0.6836 - val_loss: 0.5112 - val_accuracy: 0.8455
Epoch 4/10
663/663 [==============================] - 208s 314ms/step - loss: 0.8824 - accuracy: 0.7458 - val_loss: 0.4561 - val_accuracy: 0.8625
Epoch 5/10
663/663 [==============================] - 208s 314ms/step - loss: 0.7599 - accuracy: 0.7782 - val_loss: 0.4586 - val_accuracy: 0.8591
Epoch 6/10
663/663 [==============================] - 208s 313ms/step - loss: 0.6157 - accuracy: 0.8117 - val_loss: 0.4180 - val_accuracy: 0.8744
Epoch 7/10
663/663 [==============================] - 208s 314ms/step - loss: 0.5763 - accuracy: 0.8342 - val_loss: 0.4616 - val_accuracy: 0.8812
Epoch 8/10
663/663 [==============================] - 208s 313ms/step - loss: 0.5286 - accuracy: 0.8453 - val_loss: 0.3921 - val_accuracy: 0.8812
Epoch 9/10
663/663 [==============================] - 208s 314ms/step - loss: 0.4275 - accuracy: 0.8723 - val_loss: 0.4639 - val_accuracy: 0.8608
Epoch 10/10
663/663 [==============================] - 208s 313ms/step - loss: 0.4304 - accuracy: 0.8655 - val_loss: 0.4820 - val_accuracy: 0.8625

In [ ]:
model.trainable =  True

In [ ]:
model.compile(loss = 'categorical_crossentropy',
             optimizer = Adam(learning_rate = 0.00001),
             metrics = ['accuracy'])

In [ ]:
history = model.fit(train_generator,epochs = 5,
                    validation_data = val_generator)

Epoch 1/5
663/663 [==============================] - 226s 318ms/step - loss: 0.3778 - accuracy: 0.8862 - val_loss: 0.4411 - val_accuracy: 0.8795
Epoch 2/5
663/663 [==============================] - 208s 313ms/step - loss: 0.3354 - accuracy: 0.8933 - val_loss: 0.3567 - val_accuracy: 0.8896
Epoch 3/5
663/663 [==============================] - 208s 314ms/step - loss: 0.2902 - accuracy: 0.9080 - val_loss: 0.3385 - val_accuracy: 0.9032
Epoch 4/5
663/663 [==============================] - 208s 314ms/step - loss: 0.2790 - accuracy: 0.9078 - val_loss: 0.3618 - val_accuracy: 0.8998
Epoch 5/5
663/663 [==============================] - 208s 314ms/step - loss: 0.2698 - accuracy: 0.9172 - val_loss: 0.3236 - val_accuracy: 0.9185

In [ ]:
import os
dir = '/content/drive/MyDrive/animal/TEST'
images = os.listdir(dir)

In [ ]:
import numpy as np
test_res = []
for filename in images:
  test_res.append(filename)

In [ ]:
test_res

['1.jpg',
 '10.jpg',
 '100.jpg',
 '1000.jpg',
 '1001.jpg',
 '1002.jpg',
 '1003.jpg',
 '1004.jpg',
 '1005.jpg',
 '1006.jpg',
 '1007.jpg',
 '1008.jpg',
 '1009.jpg',
 '101.jpg',
 '1010.jpg',
 '1011.jpg',
 '1012.jpg',
 '1013.jpg',
 '1014.jpg',
 '1015.jpg',
 '1016.jpg',
 '1017.jpg',
 '1018.jpg',
 '1019.jpg',
 '102.jpg',
 '1020.jpg',
 '1021.jpg',
 '1022.jpg',
 '1023.jpg',
 '1024.jpg',
 '1025.jpg',
 '1026.jpg',
 '1027.jpg',
 '1028.jpg',
 '1029.jpg',
 '103.jpg',
 '1030.jpg',
 '1031.jpg',
 '1032.jpg',
 '1033.jpg',
 '1034.jpg',
 '1035.jpg',
 '1036.jpg',
 '1037.jpg',
 '1038.jpg',
 '1039.jpg',
 '104.jpg',
 '1040.jpg',
 '1041.jpg',
 '1042.jpg',
 '1043.jpg',
 '1044.jpg',
 '1045.jpg',
 '1046.jpg',
 '1047.jpg',
 '1048.jpg',
 '1049.jpg',
 '105.jpg',
 '1050.jpg',
 '1051.jpg',
 '1052.jpg',
 '1053.jpg',
 '1054.jpg',
 '1055.jpg',
 '1056.jpg',
 '1057.jpg',
 '1058.jpg',
 '1059.jpg',
 '106.jpg',
 '1060.jpg',
 '1061.jpg',
 '1062.jpg',
 '1063.jpg',
 '1064.jpg',
 '1065.jpg',
 '1066.jpg',
 '1067.jpg',
 '1068.jpg',
 '1069.jpg',
 '107.jpg',
 '1070.jpg',
 '1071.jpg',
 '1072.jpg',
 '1073.jpg',
 '1074.jpg',
 '1075.jpg',
 '1076.jpg',
 '1077.jpg',
 '1078.jpg',
 '1079.jpg',
 '108.jpg',
 '1080.jpg',
 '1081.jpg',
 '1082.jpg',
 '1083.jpg',
 '1084.jpg',
 '1085.jpg',
 '1086.jpg',
 '1087.jpg',
 '1088.jpg',
 '1089.jpg',
 '109.jpg',
 '1090.jpg',
 '1091.jpg',
 '1092.jpg',
 '1093.jpg',
 '1094.jpg',
 '1095.jpg',
 '1096.jpg',
 '1097.jpg',
 '1098.jpg',
 '1099.jpg',
 '11.jpg',
 '110.jpg',
 '1100.jpg',
 '1101.jpg',
 '1102.jpg',
 '1103.jpg',
 '1104.jpg',
 '1105.jpg',
 '1106.jpg',
 '1107.jpg',
 '1108.jpg',
 '1109.jpg',
 '111.jpg',
 '1110.jpg',
 '1111.jpg',
 '1112.jpg',
 '1113.jpg',
 '1114.jpg',
 '1115.jpg',
 '1116.jpg',
 '1117.jpg',
 '1118.jpg',
 '1119.jpg',
 '112.jpg',
 '1120.jpg',
 '1121.jpg',
 '1122.jpg',
 '1123.jpg',
 '1124.jpg',
 '1125.jpg',
 '1126.jpg',
 '1127.jpg',
 '1128.jpg',
 '1129.jpg',
 '113.jpg',
 '1130.jpg',
 '1131.jpg',
 '1132.jpg',
 '1133.jpg',
 '1134.jpg',
 '1135.jpg',
 '1136.jpg',
 '1137.jpg',
 '1138.jpg',
 '1139.jpg',
 '114.jpg',
 '1140.jpg',
 '1141.jpg',
 '1142.jpg',
 '1143.jpg',
 '1144.jpg',
 '1145.jpg',
 '1146.jpg',
 '1147.jpg',
 '1148.jpg',
 '1149.jpg',
 '115.jpg',
 '1150.jpg',
 '1151.jpg',
 '1152.jpg',
 '1153.jpg',
 '1154.jpg',
 '1155.jpg',
 '1156.jpg',
 '1157.jpg',
 '1158.jpg',
 '1159.jpg',
 '116.jpg',
 '1160.jpg',
 '1161.jpg',
 '1162.jpg',
 '1163.jpg',
 '1164.jpg',
 '1165.jpg',
 '1166.jpg',
 '1167.jpg',
 '1168.jpg',
 '1169.jpg',
 '117.jpg',
 '1170.jpg',
 '1171.jpg',
 '1172.jpg',
 '1173.jpg',
 '1174.jpg',
 '1175.jpg',
 '1176.jpg',
 '1177.jpg',
 '1178.jpg',
 '1179.jpg',
 '118.jpg',
 '1180.jpg',
 '1181.jpg',
 '1182.jpg',
 '1183.jpg',
 '1184.jpg',
 '1185.jpg',
 '1186.jpg',
 '1187.jpg',
 '1188.jpg',
 '1189.jpg',
 '119.jpg',
 '1190.jpg',
 '1191.jpg',
 '1192.jpg',
 '1193.jpg',
 '1194.jpg',
 '1195.jpg',
 '1196.jpg',
 '1197.jpg',
 '1198.jpg',
 '1199.jpg',
 '12.jpg',
 '120.jpg',
 '1200.jpg',
 '1201.jpg',
 '1202.jpg',
 '1203.jpg',
 '1204.jpg',
 '1205.jpg',
 '1206.jpg',
 '1207.jpg',
 '1208.jpg',
 '1209.jpg',
 '121.jpg',
 '1210.jpg',
 '1211.jpg',
 '1212.jpg',
 '1213.jpg',
 '1214.jpg',
 '1215.jpg',
 '1216.jpg',
 '1217.jpg',
 '1218.jpg',
 '1219.jpg',
 '122.jpg',
 '1220.jpg',
 '1221.jpg',
 '1222.jpg',
 '1223.jpg',
 '1224.jpg',
 '1225.jpg',
 '1226.jpg',
 '1227.jpg',
 '1228.jpg',
 '1229.jpg',
 '123.jpg',
 '1230.jpg',
 '1231.jpg',
 '1232.jpg',
 '1233.jpg',
 '1234.jpg',
 '1235.jpg',
 '1236.jpg',
 '1237.jpg',
 '1238.jpg',
 '1239.jpg',
 '124.jpg',
 '1240.jpg',
 '1241.jpg',
 '1242.jpg',
 '1243.jpg',
 '1244.jpg',
 '1245.jpg',
 '1246.jpg',
 '1247.jpg',
 '1248.jpg',
 '1249.jpg',
 '125.jpg',
 '1250.jpg',
 '1251.jpg',
 '1252.jpg',
 '1253.jpg',
 '1254.jpg',
 '1255.jpg',
 '1256.jpg',
 '1257.jpg',
 '1258.jpg',
 '1259.jpg',
 '126.jpg',
 '1260.jpg',
 '1261.jpg',
 '1262.jpg',
 '1263.jpg',
 '1264.jpg',
 '1265.jpg',
 '1266.jpg',
 '1267.jpg',
 '1268.jpg',
 '1269.jpg',
 '127.jpg',
 '1270.jpg',
 '1271.jpg',
 '1272.jpg',
 '1273.jpg',
 '1274.jpg',
 '1275.jpg',
 '1276.jpg',
 '1277.jpg',
 '1278.jpg',
 '1279.jpg',
 '128.jpg',
 '1280.jpg',
 '1281.jpg',
 '1282.jpg',
 '1283.jpg',
 '1284.jpg',
 '1285.jpg',
 '1286.jpg',
 '1287.jpg',
 '1288.jpg',
 '1289.jpg',
 '129.jpg',
 '1290.jpg',
 '1291.jpg',
 '1292.jpg',
 '1293.jpg',
 '1294.jpg',
 '1295.jpg',
 '1296.jpg',
 '1297.jpg',
 '1298.jpg',
 '1299.jpg',
 '13.jpg',
 '130.jpg',
 '1300.jpg',
 '1301.jpg',
 '1302.jpg',
 '1303.jpg',
 '1304.jpg',
 '1305.jpg',
 '1306.jpg',
 '1307.jpg',
 '1308.jpg',
 '1309.jpg',
 '131.jpg',
 '1310.jpg',
 '1311.jpg',
 '1312.jpg',
 '1313.jpg',
 '1314.jpg',
 '1315.jpg',
 '1316.jpg',
 '1317.jpg',
 '1318.jpg',
 '1319.jpg',
 '132.jpg',
 '1320.jpg',
 '1321.jpg',
 '1322.jpg',
 '1323.jpg',
 '1324.jpg',
 '1325.jpg',
 '1326.jpg',
 '1327.jpg',
 '1328.jpg',
 '1329.jpg',
 '133.jpg',
 '1330.jpg',
 '1331.jpg',
 '1332.jpg',
 '1333.jpg',
 '1334.jpg',
 '1335.jpg',
 '1336.jpg',
 '1337.jpg',
 '1338.jpg',
 '1339.jpg',
 '134.jpg',
 '1340.jpg',
 '1341.jpg',
 '1342.jpg',
 '1343.jpg',
 '1344.jpg',
 '1345.jpg',
 '1346.jpg',
 '1347.jpg',
 '1348.jpg',
 '1349.jpg',
 '135.jpg',
 '1350.jpg',
 '1351.jpg',
 '1352.jpg',
 '1353.jpg',
 '1354.jpg',
 '1355.jpg',
 '1356.jpg',
 '1357.jpg',
 '1358.jpg',
 '1359.jpg',
 '136.jpg',
 '1360.jpg',
 '1361.jpg',
 '1362.jpg',
 '1363.jpg',
 '1364.jpg',
 '1365.jpg',
 '1366.jpg',
 '1367.jpg',
 '1368.jpg',
 '1369.jpg',
 '137.jpg',
 '1370.jpg',
 '1371.jpg',
 '1372.jpg',
 '1373.jpg',
 '1374.jpg',
 '1375.jpg',
 '1376.jpg',
 '1377.jpg',
 '1378.jpg',
 '1379.jpg',
 '138.jpg',
 '1380.jpg',
 '1381.jpg',
 '1382.jpg',
 '1383.jpg',
 '1384.jpg',
 '1385.jpg',
 '1386.jpg',
 '1387.jpg',
 '1388.jpg',
 '1389.jpg',
 '139.jpg',
 '1390.jpg',
 '1391.jpg',
 '1392.jpg',
 '1393.jpg',
 '1394.jpg',
 '1395.jpg',
 '1396.jpg',
 '1397.jpg',
 '1398.jpg',
 '1399.jpg',
 '14.jpg',
 '140.jpg',
 '1400.jpg',
 '1401.jpg',
 '1402.jpg',
 '1403.jpg',
 '1404.jpg',
 '1405.jpg',
 '1406.jpg',
 '1407.jpg',
 '1408.jpg',
 '1409.jpg',
 '141.jpg',
 '1410.jpg',
 '1411.jpg',
 '1412.jpg',
 '1413.jpg',
 '1414.jpg',
 '1415.jpg',
 '1416.jpg',
 '1417.jpg',
 '1418.jpg',
 '1419.jpg',
 '142.jpg',
 '1420.jpg',
 '1421.jpg',
 '1422.jpg',
 '1423.jpg',
 '1424.jpg',
 '1425.jpg',
 '1426.jpg',
 '1427.jpg',
 '1428.jpg',
 '1429.jpg',
 '143.jpg',
 '1430.jpg',
 '1431.jpg',
 '1432.jpg',
 '1433.jpg',
 '1434.jpg',
 '1435.jpg',
 '1436.jpg',
 '1437.jpg',
 '1438.jpg',
 '1439.jpg',
 '144.jpg',
 '1440.jpg',
 '1441.jpg',
 '1442.jpg',
 '1443.jpg',
 '1444.jpg',
 '1445.jpg',
 '1446.jpg',
 '1447.jpg',
 '1448.jpg',
 '1449.jpg',
 '145.jpg',
 '1450.jpg',
 '1451.jpg',
 '1452.jpg',
 '1453.jpg',
 '1454.jpg',
 '1455.jpg',
 '1456.jpg',
 '1457.jpg',
 '1458.jpg',
 '1459.jpg',
 '146.jpg',
 '1460.jpg',
 '1461.jpg',
 '1462.jpg',
 '1463.jpg',
 '1464.jpg',
 '1465.jpg',
 '1466.jpg',
 '1467.jpg',
 '1468.jpg',
 '1469.jpg',
 '147.jpg',
 '1470.jpg',
 '1471.jpg',
 '1472.jpg',
 '1473.jpg',
 '1474.jpg',
 '1475.jpg',
 '1476.jpg',
 '1477.jpg',
 '1478.jpg',
 '1479.jpg',
 '148.jpg',
 '1480.jpg',
 '1481.jpg',
 '1482.jpg',
 '1483.jpg',
 '1484.jpg',
 '1485.jpg',
 '1486.jpg',
 '1487.jpg',
 '1488.jpg',
 '1489.jpg',
 '149.jpg',
 '1490.jpg',
 '1491.jpg',
 '1492.jpg',
 '1493.jpg',
 '1494.jpg',
 '1495.jpg',
 '1496.jpg',
 '1497.jpg',
 '1498.jpg',
 '1499.jpg',
 '15.jpg',
 '150.jpg',
 '1500.jpg',
 '151.jpg',
 '152.jpg',
 '153.jpg',
 '154.jpg',
 '155.jpg',
 '156.jpg',
 '157.jpg',
 '158.jpg',
 '159.jpg',
 '16.jpg',
 '160.jpg',
 '161.jpg',
 '162.jpg',
 '163.jpg',
 '164.jpg',
 '165.jpg',
 '166.jpg',
 '167.jpg',
 '168.jpg',
 '169.jpg',
 '17.jpg',
 '170.jpg',
 '171.jpg',
 '172.jpg',
 '173.jpg',
 '174.jpg',
 '175.jpg',
 '176.jpg',
 '177.jpg',
 '178.jpg',
 '179.jpg',
 '18.jpg',
 '180.jpg',
 '181.jpg',
 '182.jpg',
 '183.jpg',
 '184.jpg',
 '185.jpg',
 '186.jpg',
 '187.jpg',
 '188.jpg',
 '189.jpg',
 '19.jpg',
 '190.jpg',
 '191.jpg',
 '192.jpg',
 '193.jpg',
 '194.jpg',
 '195.jpg',
 '196.jpg',
 '197.jpg',
 '198.jpg',
 '199.jpg',
 '2.jpg',
 '20.jpg',
 '200.jpg',
 '201.jpg',
 '202.jpg',
 '203.jpg',
 '204.jpg',
 '205.jpg',
 '206.jpg',
 '207.jpg',
 '208.jpg',
 '209.jpg',
 '21.jpg',
 '210.jpg',
 '211.jpg',
 '212.jpg',
 '213.jpg',
 '214.jpg',
 '215.jpg',
 '216.jpg',
 '217.jpg',
 '218.jpg',
 '219.jpg',
 '22.jpg',
 '220.jpg',
 '221.jpg',
 '222.jpg',
 '223.jpg',
 '224.jpg',
 '225.jpg',
 '226.jpg',
 '227.jpg',
 '228.jpg',
 '229.jpg',
 '23.jpg',
 '230.jpg',
 '231.jpg',
 '232.jpg',
 '233.jpg',
 '234.jpg',
 '235.jpg',
 '236.jpg',
 '237.jpg',
 '238.jpg',
 '239.jpg',
 '24.jpg',
 '240.jpg',
 '241.jpg',
 '242.jpg',
 '243.jpg',
 '244.jpg',
 '245.jpg',
 '246.jpg',
 '247.jpg',
 '248.jpg',
 '249.jpg',
 '25.jpg',
 '250.jpg',
 '251.jpg',
 '252.jpg',
 '253.jpg',
 '254.jpg',
 '255.jpg',
 '256.jpg',
 '257.jpg',
 '258.jpg',
 '259.jpg',
 '26.jpg',
 '260.jpg',
 '261.jpg',
 '262.jpg',
 '263.jpg',
 '264.jpg',
 '265.jpg',
 '266.jpg',
 '267.jpg',
 '268.jpg',
 '269.jpg',
 '27.jpg',
 '270.jpg',
 '271.jpg',
 '272.jpg',
 '273.jpg',
 '274.jpg',
 '275.jpg',
 '276.jpg',
 '277.jpg',
 '278.jpg',
 '279.jpg',
 '28.jpg',
 '280.jpg',
 '281.jpg',
 '282.jpg',
 '283.jpg',
 '284.jpg',
 '285.jpg',
 '286.jpg',
 '287.jpg',
 '288.jpg',
 '289.jpg',
 '29.jpg',
 '290.jpg',
 '291.jpg',
 '292.jpg',
 '293.jpg',
 '294.jpg',
 '295.jpg',
 '296.jpg',
 '297.jpg',
 '298.jpg',
 '299.jpg',
 '3.jpg',
 '30.jpg',
 '300.jpg',
 '301.jpg',
 '302.jpg',
 '303.jpg',
 '304.jpg',
 '305.jpg',
 '306.jpg',
 '307.jpg',
 '308.jpg',
 '309.jpg',
 '31.jpg',
 '310.jpg',
 '311.jpg',
 '312.jpg',
 '313.jpg',
 '314.jpg',
 '315.jpg',
 '316.jpg',
 '317.jpg',
 '318.jpg',
 '319.jpg',
 '32.jpg',
 '320.jpg',
 '321.jpg',
 '322.jpg',
 '323.jpg',
 '324.jpg',
 '325.jpg',
 '326.jpg',
 '327.jpg',
 '328.jpg',
 '329.jpg',
 '33.jpg',
 '330.jpg',
 '331.jpg',
 '332.jpg',
 '333.jpg',
 '334.jpg',
 '335.jpg',
 '336.jpg',
 '337.jpg',
 '338.jpg',
 '339.jpg',
 '34.jpg',
 '340.jpg',
 '341.jpg',
 '342.jpg',
 '343.jpg',
 '344.jpg',
 '345.jpg',
 '346.jpg',
 '347.jpg',
 '348.jpg',
 '349.jpg',
 '35.jpg',
 '350.jpg',
 '351.jpg',
 '352.jpg',
 '353.jpg',
 '354.jpg',
 '355.jpg',
 '356.jpg',
 '357.jpg',
 '358.jpg',
 '359.jpg',
 '36.jpg',
 '360.jpg',
 '361.jpg',
 '362.jpg',
 '363.jpg',
 '364.jpg',
 '365.jpg',
 '366.jpg',
 '367.jpg',
 '368.jpg',
 '369.jpg',
 '37.jpg',
 '370.jpg',
 '371.jpg',
 '372.jpg',
 '373.jpg',
 '374.jpg',
 '375.jpg',
 '376.jpg',
 '377.jpg',
 '378.jpg',
 '379.jpg',
 '38.jpg',
 '380.jpg',
 '381.jpg',
 '382.jpg',
 '383.jpg',
 '384.jpg',
 '385.jpg',
 '386.jpg',
 '387.jpg',
 '388.jpg',
 '389.jpg',
 '39.jpg',
 '390.jpg',
 '391.jpg',
 '392.jpg',
 '393.jpg',
 '394.jpg',
 '395.jpg',
 '396.jpg',
 '397.jpg',
 '398.jpg',
 '399.jpg',
 '4.jpg',
 '40.jpg',
 '400.jpg',
 '401.jpg',
 '402.jpg',
 '403.jpg',
 '404.jpg',
 '405.jpg',
 '406.jpg',
 '407.jpg',
 '408.jpg',
 '409.jpg',
 '41.jpg',
 '410.jpg',
 '411.jpg',
 '412.jpg',
 '413.jpg',
 '414.jpg',
 '415.jpg',
 '416.jpg',
 '417.jpg',
 '418.jpg',
 '419.jpg',
 '42.jpg',
 '420.jpg',
 '421.jpg',
 '422.jpg',
 '423.jpg',
 '424.jpg',
 '425.jpg',
 '426.jpg',
 '427.jpg',
 '428.jpg',
 '429.jpg',
 '43.jpg',
 '430.jpg',
 '431.jpg',
 '432.jpg',
 '433.jpg',
 '434.jpg',
 '435.jpg',
 '436.jpg',
 '437.jpg',
 '438.jpg',
 '439.jpg',
 '44.jpg',
 '440.jpg',
 '441.jpg',
 '442.jpg',
 '443.jpg',
 '444.jpg',
 '445.jpg',
 '446.jpg',
 '447.jpg',
 '448.jpg',
 '449.jpg',
 '45.jpg',
 '450.jpg',
 '451.jpg',
 '452.jpg',
 '453.jpg',
 '454.jpg',
 '455.jpg',
 '456.jpg',
 '457.jpg',
 '458.jpg',
 '459.jpg',
 '46.jpg',
 '460.jpg',
 '461.jpg',
 '462.jpg',
 '463.jpg',
 '464.jpg',
 '465.jpg',
 '466.jpg',
 '467.jpg',
 '468.jpg',
 '469.jpg',
 '47.jpg',
 '470.jpg',
 '471.jpg',
 '472.jpg',
 '473.jpg',
 '474.jpg',
 '475.jpg',
 '476.jpg',
 '477.jpg',
 '478.jpg',
 '479.jpg',
 '48.jpg',
 '480.jpg',
 '481.jpg',
 '482.jpg',
 '483.jpg',
 '484.jpg',
 '485.jpg',
 '486.jpg',
 '487.jpg',
 '488.jpg',
 '489.jpg',
 '49.jpg',
 '490.jpg',
 '491.jpg',
 '492.jpg',
 '493.jpg',
 '494.jpg',
 '495.jpg',
 '496.jpg',
 '497.jpg',
 '498.jpg',
 '499.jpg',
 '5.jpg',
 '50.jpg',
 '500.jpg',
 '501.jpg',
 '502.jpg',
 '503.jpg',
 '504.jpg',
 '505.jpg',
 '506.jpg',
 '507.jpg',
 '508.jpg',
 '509.jpg',
 '51.jpg',
 '510.jpg',
 '511.jpg',
 '512.jpg',
 '513.jpg',
 '514.jpg',
 '515.jpg',
 '516.jpg',
 '517.jpg',
 '518.jpg',
 '519.jpg',
 '52.jpg',
 '520.jpg',
 '521.jpg',
 '522.jpg',
 '523.jpg',
 '524.jpg',
 '525.jpg',
 '526.jpg',
 '527.jpg',
 '528.jpg',
 '529.jpg',
 '53.jpg',
 '530.jpg',
 '531.jpg',
 '532.jpg',
 '533.jpg',
 '534.jpg',
 '535.jpg',
 '536.jpg',
 '537.jpg',
 '538.jpg',
 '539.jpg',
 '54.jpg',
 '540.jpg',
 '541.jpg',
 '542.jpg',
 '543.jpg',
 '544.jpg',
 '545.jpg',
 '546.jpg',
 '547.jpg',
 '548.jpg',
 ...]

In [ ]:
test_result = []
for filename in images:
  img = image.load_img(path="/content/drive/MyDrive/animal/TEST/"+str(filename) ,target_size=(200, 200,3))
  img_array = image.img_to_array(img)
  img_batch = np.expand_dims(img_array, axis=0)
  pred = model.predict(img_batch)
  prediction= np.argmax(pred,axis=1)
  test_result.append(prediction)

In [ ]:
pred = np.array(test_result)

In [ ]:
pred

array([[34],
       [25],
       [10],
       ...,
       [34],
       [34],
       [ 1]])

In [ ]:
pred1 = pred.tolist()

In [ ]:
pred2 = np.array(pred).ravel()

In [ ]:
pred2

array([34, 25, 10, ..., 34, 34,  1])

In [ ]:
labels = (val_generator.class_indices)
labels = dict((v,k) for k,v in labels.items())
pred = [labels[k] for k in pred2]

In [ ]:
df1 = train_x['Type'].values

In [ ]:
len(pred)

1500

In [ ]:
# confusion_matrix(df1, pred)

In [ ]:
df3 = pd.DataFrame(list(zip(images, pred)),columns = ['Filename','Labels'])

In [ ]:
df3

      Filename                      Labels
0        1.jpg  staffordshire_bull_terrier
1       10.jpg                         pug
2      100.jpg                   chihuahua
3     1000.jpg          miniature_pinscher
4     1001.jpg                  pomeranian
...        ...                         ...
1495   995.jpg                russian_blue
1496   996.jpg           british_shorthair
1497   997.jpg  staffordshire_bull_terrier
1498   998.jpg  staffordshire_bull_terrier
1499   999.jpg            american_bulldog

[1500 rows x 2 columns]

In [ ]:
df3.to_csv("/content/animal3.csv", index = False)